### ISSUE TITLE
Searching by email content when filtered by email brings up doubled email results

### ISSUE THREAD

**Issue by AnaScarlet** [stephen-kruger/bluebox#15]
Issue: I am seeing doubles of certain emails in the search results.

Steps to reproduce:
1. Filter by email address first (`test_sst_fvt_operations_user_01`)
2. Search for an email subject that occurs in more than one email (`OMS NA`)
3. Count the emails = 25. Look at identifying features of each email (there are, for example, 2 emails with `fvt01` in them when there should be 1). 
4. Refresh the page to clear the search. Count the emails with this subject in them without the search (the ones with `OMS NA` in them were all received in a row in one day). There are 21 emails and identifying features of emails are correct (1 email with `fvt01` in its subject).

**Comment by stephen-kruger** [comment]
Can you try the latest 4.7.0 release and see if it works?
Please follow the instructions in the README, and use the right server.xml etc
