### ISSUE TITLE
Symbolic link to webapps directory does not exist in RPM

### ISSUE THREAD

**Issue by brianhussey** [stephen-kruger/bluebox#4]
Hi Stephen,
Tthe war file is generated in /var/lib/tomcat6/webapps/ and originally it was creating a symbolic link between that directory and /opt/tomcat6/webapps/ but in version bluebox-4.3.4-1.noarch it's not.

To work around it I've run:
rm -rf /opt/tomcat/webapps/
ln -s /var/lib/tomcat6/webapps/ /opt/tomcat/

Thanks,
Brian

**Comment by stephen-kruger** [comment]
The tomcat6 RH dependancy should be always installed in /var/lib/tomcat6/webapps
