### ISSUE TITLE
Problem for creating a new address 

### ISSUE THREAD

**Issue by Christina-Maillot-FrenchPDC** [stephen-kruger/bluebox#6]
Hello Stephen
I have tried to use Bluebox sending an email to the address : **chris_AAA@bluebox.lotus.com**
I dont see any email for this address on  http://bluebox.lotus.com/ 
and I receive a delivery failure report - see attached image 
![delivery failure report](https://user-images.githubusercontent.com/31500944/30217206-c2432984-94b5-11e7-9baa-f1299c2bb0ba.JPG)

Could you help me ? not sure I have done all I need to do ..
Thanks 
Christina

**Comment by stephen-kruger** [comment]
Hi Christina,

bluebox.lotus.com is on the intranet, so if you are sending mail from outside the intranet that hostname will not resolve.
There is an external facing server which should be used instead - please check on the Bluebox community on w3 for details on how to access.

**Comment by Christina-Maillot-FrenchPDC** [comment]
Thanks for your answer Stephen
Actually , I was sending mail from **INSIDE** the intranet.. 
I have tried to find some help on Bluebox community but not found for the moment 
Thanks in advance if you have an idea for this issue : my objective was to create several users in order to make some tests on a new application.
Christina

**Comment by stephen-kruger** [comment]
Check what system you are using to send the mail. For example it might have an smtp server configuration. That smtp server needs to be in intranet.
You can also try : 
telnet bluebox.lotus.com 25 
from the machine sending emails - it should allow connection and show the bluebox server prompt.

If you inspect the raw content of the rejected mail (look at the headers) it will show the route the mail took when delivery failed - that will show you which routing smtp server could not access the intranet. For example I think the Lotus mail now uses SmartCloud - that is external, and will not be able to forward mail to the intranet.
On the Community you can find the link and access log to the external bluebox server - that one should work for you.
