### ISSUE TITLE
Available bluebox servers

### ISSUE THREAD

**Issue by simonnaegele** [stephen-kruger/bluebox#7]
Stephen, are there any IBM bluebox servers available that can be reached from Internet? We would need them for test automation of a production system.

**Comment by stephen-kruger** [comment]
There are : https://bluebox.ams01.isc4sb.com/bluebox/app/inbox.jsp

No idea who manages it or what the password is...

**Comment by simonnaegele** [comment]
Thanks a lot Stephen! It's hard to find out who manages it. Your manager Brian was not able to find any contact I could ask for access to that. So if you remember any name/contact who might know it would be appreciated.

**Comment by stephen-kruger** [comment]
Probably still owned by SmartCloud sys ops team. Someone in Bluemix ops team should be able to look up the owner of that machine - or try find the SmartCloud QA leads who will be using it.
The names I had down in memory are unfortunately no longer with IBM.
